version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: companydemo
    restart: always
    command: --check-caps false
    ports: 
      - 51773:1972
      - 52773:52773
    volumes:
      - ./:/irisdev/app
